### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by zackarychapple** [zackarychapple/ngTalks#1]
- [ ] Get basic app with routing going
- [ ] Get basic demo app going
- [ ] Get basic ionic app going
- [ ] Get bazel build going
- [ ] Get build going on travis or circle 
- [ ] Get basic jQuery app going
- [ ] Show material and wrapped material existing side by side
- [ ] Show ionic and wrapped ionic existing side by side
- [ ] Pull molecules and organisms into jQuery app
